name: account
version: "3.8"
services:

  db:
    image: postgres:16
    volumes:
      - "postgres:/var/lib/postgresql/data"
    env_file:
      - .env

  be:
    build: .
    image: rails_be
    command: bundle exec rails s -b 0.0.0.0 -p $PORT
    volumes:
      - ".:/be"
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres:

