version: "3.8"
services:

  db:
    image: postgres:16
    volumes:
      - "postgres:/var/lib/postgresql/data"
    env_file:
      - .env

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - ".:/accounting"
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres:

