name: main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  POSTGRES_USER: postgres
  POSTGRES_DB: test
  POSTGRES_HOST: localhost

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - name: Install system dependencies
        run: sudo apt install -yqq libpq-dev

      - name: Install Bundler & Gems
        run: |
          gem install bundler
          bundle install

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - name: Install Bundler & Gems
        run: |
          gem install bundler
          bundle install

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h 127.0.0.1 -p 5432; do
            echo "Waiting for PostgreSQL...";
            sleep 5;
          done

      - name: Setup database
        run: |
          cp config/database.ci.yml config/database.yml
          cat config/database.yml
          bundle exec rails db:schema:load

      - name: Run Tests
        run: bundle exec rspec --format progress