name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_PROD: ${{ secrets.POSTGRES_DB_PROD }}

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_DB_PROD: ${{ secrets.POSTGRES_DB_PROD }}
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - uses: Borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler
      
      - name: Install Gems
        run: |
          bundle install

      - name: Setup Database
        run: |
          bundle exec rails db:prepare
          bundle exec rake test

      - name: Build and test with rspec
        run: |
          bundle exec rspec spec
