name: main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - name: Install system dependencies
        run: sudo apt install -yqq libpq-dev

      - name: Install Bundler & Gems
        run: |
          gem install bundler
          bundle install

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_DB_PROD: ${{ secrets.POSTGRES_DB_PROD }}
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - name: Install Bundler & Gems
        run: |
          gem install bundler
          bundle install

      - name: Setup Database
        run: bundle exec rails db:prepare

      - name: Run tests with RSpec
        run: bundle exec rspec spec